version: '3'

services:
  postgresql:
    image: thehyve/ohdsi_postgresql
    ports:
      - 5432:5432
    networks:
      - app
    volumes:
      - postgresql_data:/bitnami/postgresql
#      - ./postgres:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=ohdsi
      - BITNAMI_DEBUG=true

  jupyter:
    image: jupyter/r-notebook
    command: start-notebook.sh --NotebookApp.password='sha1:f7105c4fb85e:5d1b80e5fe40f641268ad01db47da046f6e66698'
    networks:
      - app
    ports:
      - 8888:8888
    volumes:
      - jupyter:/home/jovyan/work
    environment:
      - RESTARTABLE=yes

  etl:
    command: python main.py
    build:
      context: .
    networks:
      - app
    restart: on-failure
#    volumes:
#      - ./logs:/app/logs
    environment:
      - ETL_HOSTNAME=postgresql
      - ETL_PORT=5432
      - ETL_DATABASE=ohdsi
      - ETL_USERNAME=admin
      - ETL_PASSWORD=secret
      - ETL_SOURCE=/app/resources/test_datasets/1000_records
      - ETL_DEBUG=False
      - ETL_SKIPVOCAB=False

volumes:
  postgresql_data:
    driver: local

networks:
  app:
